#!/usr/bin/env python3
"""Generate a host-side `host_config.local.yaml` for browser-env.

The shipped `browser_env/host_config.yaml` uses ABSOLUTE container paths
(/app/...) and the real `playwright` backend. That is correct inside the image
but wrong on a developer machine. This script rewrites the two paths that must
point at the local checkout and lets you pick the backend.

    python3 scripts/make_local_config.py                 # scripted (no browser needed)
    python3 scripts/make_local_config.py --backend playwright
    python3 scripts/make_local_config.py --out /tmp/browser_host.yaml

Every value written is explicit — the script never leaves a path relative,
because a relative ROOT is exactly the class of silent default the plugins
reject at startup. There is no task file: tasks live outside the environment
and are supplied by the caller on env/reset.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def main() -> int:
    here = Path(__file__).resolve().parent
    repo = here.parent                       # browser-env/
    default_out = repo / "browser_env" / "host_config.local.yaml"

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--backend", choices=["scripted", "playwright"],
                    default="scripted",
                    help="browser backend to write into the config")
    ap.add_argument("--port", type=int, default=8770)
    ap.add_argument("--root", default="/tmp/a2e/browser",
                    help="episode/experience store root")
    ap.add_argument("--out", default=str(default_out))
    args = ap.parse_args()

    out = Path(args.out).resolve()
    os.makedirs(args.root, exist_ok=True)

    config = f"""# GENERATED by scripts/make_local_config.py — do not edit by hand.
# Host-side config: absolute local paths, backend={args.backend}.
host_id: "browser-env-local"

transport:
  type: http
  config:
    base_url: "http://localhost:{args.port}"
    send_path: "/send"
    stream_path: "/stream"

server:
  host: "0.0.0.0"
  port: {args.port}

auth_token: null

audit:
  enabled: true
  path: "{args.root}/audit.log"
  rotate:
    max_bytes: 10485760
    backup_count: 5
  session_id_source: host_id

snapshot_store:
  type: file
  config:
    root: "{args.root}"

plugins:
  - name: browser_env
    type: env
    cls: browser_env.plugin.BrowserEnvPlugin
    metadata:
      enabled: true
      priority: 0
      exclusive: false
      BACKEND: "{args.backend}"
      HEADLESS: true
      BROWSER: "chromium"
      ROOT: "{args.root}"
      DEFAULT_MAX_STEPS: 15
      MAX_TEXT_CHARS: 4000
      MAX_ELEMENTS: 120
      BROWSER_TIMEOUT_MS: 15000
      STEP_PENALTY: 0.0
      PROGRESS_REWARD: 0.0

  - name: browser_tools
    type: tools
    cls: browser_env.browser_tool.BrowserToolPlugin
    metadata:
      enabled: true
      priority: 5
      exclusive: false
      ENV_PLUGIN: "browser_env"
      DEFAULT_URL: ""
      MAX_TEXT_CHARS: 4000
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(config)
    print(f"wrote {out}")
    print(f"  backend : {args.backend}")
    print(f"  tasks   : {tasks}")
    print(f"  root    : {args.root}")
    print(f"  port    : {args.port}")
    return 0


if __name__ == "__main__":
    sys.exit(main())